### PR TITLE
Make tests pass on 1.2

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by xukai92** [comment]
@mohamed82008 As reported before the type stable syntax is broken in Julia 1.2. Can you take a look on how to fix it?

**Comment by mohamed82008** [comment]
Sure, I will take a look this weekend.

**Comment by xukai92** [comment]
@mohamed82008

**Comment by mohamed82008** [comment]
My Windows attempt to develop Turing failed, I will try Linux.

**Comment by mohamed82008** [comment]
https://github.com/JuliaLang/julia/issues/33270

**Comment by yebai** [comment]
> JuliaLang/julia#33270

This issue got fixed on Julia's mater branch.  Can we copy-and-paste the fix into Turing before Julia got a new release?

**Comment by mohamed82008** [comment]
We can do that. I will make a PR.

**Comment by mohamed82008** [comment]
I pushed a fix borrowed from the PR. If tests pass, this is ready.

**Pull request merged**
