### PR TITLE
Widen Optimization compat to v4, and related packages accordingly

### PR DESCRIPTION
**Pull request by mhauru**
Supersedes a bunch of CompatHelper PRs that did this bit-by-bit.

### CODE REVIEW

**Review by torfjelde — APPROVED** [review]
Lovely @mhauru :)

**Comment by penelopeysm** [comment]
merging so that compathelper doesn't reopen the same prs again

**Comment by mhauru** [comment]
The tests seemed to be failing. Did we understand why?

**Comment by penelopeysm** [comment]
Seems to be upstream method ambiguities https://github.com/JuliaDiff/ForwardDiff.jl/issues/681

**Comment by penelopeysm** [comment]
Will revert

**Pull request merged**
