### PR TITLE
Some style improvements

### PR DESCRIPTION
**Pull request by willtebbutt**
Supersedes #580 (which I will close, and whose branch I will delete). Really just sorts out some style-related problems.

### CODE REVIEW

**Comment by yebai** [comment]
It seems this causes a broken test. 

```julia
model_macro.jl: Test Failed at /home/travis/build/TuringLang/Turing.jl/test/compiler.jl/model_macro.jl:55
  Expression: ≈(mean((f0_mm() for _ = 1:1000)), 0.0, atol=0.1)
   Evaluated: 0.12190232025842371 ≈ 0.0 (atol=0.1) 
```

**Comment by willtebbutt** [comment]
Weird. Seemed to be fine on my machine, but I'll test again. Might be that we need a few more samples for this one.

**Comment by willtebbutt** [comment]
Confirmed that tests still pass on my machine. @yebai could you run on yours to see if there's an issue?

**Comment by yebai** [comment]
Seems like a random number issue - the tests also pass on my machine.

**Pull request merged**
