### PR TITLE
WIP: Ensuring distributions are differentiable

### PR DESCRIPTION
**Pull request by willtebbutt**
The purpose of this WIP is to ensure that we know for sure which distributions are differentiable, and which are not, so that we can know for sure what's not supported. Relevant to #674 .

ToDo:

- [ ] Cont univariate distributions
- [x] Discrete univariate distributions
- [ ] Truncated distributions
- [ ] Cont multivariate distributions
- [ ] Discrete multivariate distributions
- [ ] Cont matrix-variate distributions
- [ ] Remove old testing, targeting specific distributions in favour of new format.

### CODE REVIEW

**Comment by willtebbutt** [comment]
The interesting stuff is from line 165 onwards. Changes before that are just me re-arranging the existing tests a bit, and will be completely removed in this PR anyway.

**Comment by willtebbutt** [comment]
Current failures are known issues.

**Comment by xukai92** [comment]
What's the plan for this issue?

**Comment by willtebbutt** [comment]
I'm not actively working on this as I'm overloaded with other stuff. Happy for someone to take over, or we can continue to address on an ad-hoc basis.

**Comment by mohamed82008** [comment]
Univariate continuous:
- [ ] Arcsine
- [ ] Beta
- [ ] BetaPrime
- [ ] Biweight
- [ ] Cauchy
- [ ] Chernoff
- [ ] Chi
- [ ] Chisq
- [ ] Cosine
- [ ] Epanechnikov
- [ ] Erlang
- [ ] Exponential
- [ ] FDist
- [ ] Frechet
- [ ] Gamma
- [ ] GeneralizedExtremeValue
- [ ] GeneralizedPareto
- [ ] Gumbel
- [ ] InverseGamma
- [ ] InverseGaussian
- [ ] Kolmogorov
- [ ] KSDist
- [ ] KSOneSided
- [ ] Laplace
- [ ] Levy
- [ ] LocationScale
- [ ] Logistic
- [ ] LogitNormal
- [ ] LogNormal
- [ ] NoncentralBeta
- [ ] NoncentralChisq
- [ ] NoncentralF
- [ ] NoncentralT
- [ ] Normal
- [ ] NormalCanon
- [ ] NormalInverseGaussian
- [ ] Pareto
- [ ] PGeneralizedGaussian
- [ ] Rayleigh
- [ ] Semicircle
- [ ] StudentizedRange
- [ ] SymTriangularDist
- [ ] TDist
- [ ] TriangularDist
- [ ] Triweight
- [ ] Uniform
- [ ] VonMises
- [ ] Weibull

**Comment by mohamed82008** [comment]
Pretty much all univariate distributions are done. Some fail or error, so I will look into them.

**Comment by mohamed82008** [comment]
I updated the checklist. Many distributions are broken for various reasons. Most of them are due to dispatch errors which require defining additional methods and possibly types to bypass type restrictions in `Distributions.jl`. Relaxing those restrictions may also be possible in some cases. Three distributions (`KSDist`, `KSOneSided`, and `StudentizedRange`) are broken in `Distributions.jl` itself even without autodiff. Three distributions (`Uniform`, `Semicircle` and `VonMises`) are broken for mysterious reasons and need further investigation. Finally, I haven't done the matrix distributions yet.

**Comment by mohamed82008** [comment]
Closing this PR in favor of the newly registered package [DistributionsAD](https://github.com/TuringLang/DistributionsAD.jl). Will open another PR to use the new package.

**Pull request closed without merging**
