### PR TITLE
Fix a bug in `find_good_eps`

### PR DESCRIPTION
**Pull request by xukai92**
I guess we lost these lines of reverting theta and log-joint during some previous refactoring...

### CODE REVIEW

**Comment by yebai** [comment]
@xukai92 seems some tests are broken with this PR.

**Comment by xukai92** [comment]
Seems due to the change of stochastic processes and the random seed was a bit unlucky and lead to a mean exceeding the tolerance.

**Comment by yebai** [comment]
@xukai92 The code looks good to me. However, does this actually influence anything except the initialization for HMC, since the `find_good_eps` is only called before HMC begins?

**Comment by xukai92** [comment]
It only influences the initialisation of HMC.

**Pull request merged**
