### PR TITLE
Fix matrix_support InverseWishart test

### PR DESCRIPTION
**Pull request by mohamed82008**
Fixes some test failures for InverseWishart tests.

### CODE REVIEW

**Comment by mohamed82008** [comment]
Please don't merge.

**Comment by yebai** [comment]
> Please don't merge.

Is this PR ready for merging now?

**Comment by mohamed82008** [comment]
No, I need to check some tests that failed locally because of this.

**Comment by mohamed82008** [comment]
They also failed on Travis https://travis-ci.org/TuringLang/Turing.jl/jobs/490861083#L740

**Comment by yebai** [comment]
Fixed by  eaa6ed5?

**Pull request closed without merging**
