### PR TITLE
Twin PR to DPPL 191

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR removes some methods that should be implemented in DynamicPPL and were implemented in https://github.com/TuringLang/DynamicPPL.jl/pull/191.

### CODE REVIEW

**Review by devmotion — CHANGES_REQUESTED** [review]
Looks good, just bump the version, both of Turing and DynamicPPL :stuck_out_tongue: At least for DynamicPPL this is mandatory :slightly_smiling_face:

**Comment by torfjelde** [comment]
Should we do the same with this @devmotion ? And bound the DPPL version accordingly?

**Comment by devmotion** [comment]
Yes but maybe let's wait for https://github.com/JuliaRegistries/General/pull/26292.

**Review by devmotion — APPROVED** [review]
LGTM, I just updated the Project.toml files.

**Review by torfjelde — APPROVED** [review]
Good stuff :+1:

**Pull request merged**
