### PR TITLE
Benchmarks update

### PR DESCRIPTION
**Pull request by KDr2**
- rename `TuringBenchmarks` to `ContinuousBenchmarks.jl`
- example for using `ContinuousBenchmarks.Report.log_report`

Not ready to merge, should merge https://github.com/TuringLang/ContinuousBenchmarks.jl/pull/48 first.

### CODE REVIEW

**Comment by yebai** [comment]
@KDr2 Maybe consider allowing the user to configure the following benchmark message from `benchmarks/runbenchmarks.jl`. 

```
The benchmark job for this commit is finished.

The report is committed in this commit: TuringLang/TuringBenchmarks#5d76aa4513cffb4143266905286f6be7e3e59b02.

You can see the report at https://github.com/TuringLang/TuringBenchmarks/blob/report/jobs/BMCI-0-c410df0-201907081139.report.md.

Below is the log reported from the benchmark:
```

In general, we would like to transfer all configurations for `ContinuousBenchmarks.jl` into `benchmarks/*`.

**Comment by KDr2** [comment]
> @KDr2 Maybe consider allowing the user to configure the following benchmark message (e.g. in `benchmarks/runbenchmarks.jl`).

@yebai Done and ready to merge:
- the file `benchmark_list.jl` is renamed to `benchmark_config.jl`
- the template is configured in `benchmark_config.jl`

**Comment by KDr2** [comment]
Anyone knows the reason of the AD compatibility unit test failure?

**Comment by yebai** [comment]
> Anyone knows the reason of the AD compatibility unit test failure?

Hi @KDr2, which tests are you referring to?

**Comment by KDr2** [comment]
> Hi @KDr2, which tests are you referring to?

```
Test Summary:                        | Pass  Fail  Total
Turing                               | 3466     2   3468
  core                               |  300     2    302
    ad.jl                            |  118     2    120
      AD compatibility               |   23     2     25
```
The log is here: https://travis-ci.org/TuringLang/Turing.jl/jobs/556138382

**Pull request merged**
