### PR TITLE
Add GSoC blog post

### PR DESCRIPTION
**Pull request by cpfiffer**
Provides a brief summary of the GSoC activity. @sharanry @luiarthur @SaranjeetKaur can you guys take a look at this to make sure it accurately represents your work this summer?

### CODE REVIEW

**Comment by sharanry** [comment]
My part looks fine to me. Thanks!

**Comment by SaranjeetKaur** [comment]
Looks great! Thank you

**Comment by luiarthur** [comment]
Looks good to me. Thanks!

**Comment by devmotion** [comment]
(Some of) the test errors should be fixed by https://github.com/TuringLang/DistributionsAD.jl/pull/115.

**Comment by cpfiffer** [comment]
I'm just going to merge this through since it's a blog post.

**Pull request merged**
