### PR TITLE
Fix MvNormal and Tracker - Zhuo's trick

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR brings back the trick from #743 which is the easiest way to support Tracker in MvNormal. This is a workaround for #749 until we figure out what's wrong there. We also move from Flux.Tracker to Tracker as Tracker is now removed from Flux.

### CODE REVIEW

**Comment by mohamed82008** [comment]
https://github.com/JuliaStats/PDMats.jl/pull/90

**Comment by mohamed82008** [comment]
This PR is just awaiting a new release for PDMats.

**Comment by mohamed82008** [comment]
https://github.com/JuliaStats/PDMats.jl/issues/91

**Comment by yebai** [comment]
Thanks, let's merge it from the Turing side then.

**Pull request merged**
