### PR TITLE
Fix MH indexing bug

### PR DESCRIPTION
**Pull request by cpfiffer**
This PR fixes https://github.com/TuringLang/Turing.jl/issues/1133 by fixing a case where the Turing-side code was not passing scalars correctly to AdvancedMH. 

Currently the way I handle passing NamedTuples into Turing is not very robust (and could be more performant), so I'm doubly open to comments on this one. `set_namedtuple!` for example is a very messy and ugly function that relies far too much on heuristics.

### CODE REVIEW

**Comment by devmotion** [comment]
I'm not sure if this can be handled in a completely "nice" way at the moment. Maybe something along the lines of https://github.com/TuringLang/DynamicPPL.jl/issues/5 would be helpful.

**Comment by cpfiffer** [comment]
Looks like the test failures are due to nondeterminism in the VI suite. I'll open a separate PR to fix the test.

**Comment by cpfiffer** [comment]
I think this can go through, at the very least to fix #1133. If the comments in https://github.com/TuringLang/DynamicPPL.jl/issues/5 are addressed, I can come back to the general approach that AdvancedMH uses to integrate into Turing.

**Comment by yebai** [comment]
Maybe add a test for the error case?

**Comment by cpfiffer** [comment]
Updated to include the test for the error.

**Pull request merged**
