### PR TITLE
Added docs redesign.

### PR DESCRIPTION
**Pull request by yebai**
Live previews 
- https://gold-developer.github.io/turing-docs/ (more recent)
- https://yebai.github.io/Turing.jl/

### CODE REVIEW

**Comment by yebai** [comment]
@cpfiffer @trappmartin This is almost ready to merge - Pls take a look at the live preview. Since it's relatively easy to tweak the docs and landing page, we can always make incremental changes later.

**Comment by yebai** [comment]
@gold-developer Thanks for the help. It looks good in general. Pls find below some minor comments

- The design looks slightly weird on extra-wide screens (see screenshot below); Perhaps add a max page width for landing page and docs page 
- Math the splash background colour to the blue colour on http://mlg.eng.cam.ac.uk
- Change font family to the current one on https://turing.ml/

Screenshot 2019-07-22 at 22 33 52

**Comment by trappmartin** [comment]
I agree with Hong. It would probably be good to match the colours with those of the University of Cambridge.

Another comment. The Turing logo changes if the screen width changes. It gets squished together on a mobile devices. I think it should always rescale by keeping the proportions. As it is currently at turing.ml

**Comment by yebai** [comment]
@cpfiffer are there any other files that are automatically generated (or modified) by `Documenter.jl` other than `docs/_docs/library/api.md`?

**Comment by cpfiffer** [comment]
I can't really speak to how Documenter is supposed to work in this branch's file structure. In the current site, Documenter.jl runs through every file in [Turing.jl/docs/src](https://github.com/TuringLang/Turing.jl/tree/master/docs/src) folder, and copies the resulting files into `_site`. 

To my knowledge I believe `api.md` and [`index.md`](https://github.com/TuringLang/Turing.jl/blob/master/docs/src/index.md) are the only ones modified, but `index.md` doesn't really need to be included in the Documenter stack.

I've included this block

````
```@raw html
{% include feature_row id="main-feature_row" %}
{% include feature_row_code id="code-sample" type="right" %}
{% include feature_row id="samplers" type="left" %}
{% include feature_row id="flux" type="right" %}
{% include feature_row id="citing" type = "center-left" %}
```
````

in `index.md`, because Documenter screws up the formatting when you run this file through it. If `index.md` is moved outside the Documenter stack, the `@raw` markdown block needs to be removed.

**Comment by cpfiffer** [comment]
I'm also still getting tiling for the splash image, on Firefox:

image

**Comment by yebai** [comment]
> I can't really speak to how Documenter is supposed to work in this branch's file structure. In the current site, Documenter.jl runs through every file in Turing.jl/docs/src folder, and copies the resulting files into _site.

Perhaps merge `page` and `_docs` in this branchy into `src` to facilitate `Documenter.jl`?

**Comment by gold-developer** [comment]
@cpfiffer , I have pushed updates on hg/docs-redesign, please check it and let me know issues.

**Comment by gold-developer** [comment]
@yebai , Gemfile.lock is not compulsory.

**Comment by gold-developer** [comment]
following issues are fixed.

- extra-wide screens 
- splash background colour
- Change font family
- The "Using Turing/Sampler Visualization" link is broken

**Comment by trappmartin** [comment]
Is there a preview somewhere?

**Comment by yebai** [comment]
> Is there a preview somewhere?

https://yebai.github.io/Turing.jl/

**Comment by gold-developer** [comment]
@yebai , I couldn't do PR, as it is disabled.

**Comment by yebai** [comment]
> @yebai , I couldn't do PR, as it is disabled.

Sorry for the confusion. I mean modifying this PR (i.e. pushing new commits).

**Comment by gold-developer** [comment]
> > @yebai , I couldn't do PR, as it is disabled.
> 
> Sorry for the confusion. I mean modifying this PR (i.e. pushing new commits).

got it

**Comment by yebai** [comment]
> splash background colour

Thanks -  I think we need to improve other colours on the landing page so that it looks good. Pls see below for a reference: 

https://www.cam.ac.uk/brand-resources/guidelines/typography-and-colour/colour-palette

**Comment by gold-developer** [comment]
@yebai , in your opinion, which is the best for the landing page color?

**Comment by yebai** [comment]
> @yebai , in your opinion, which is the best for the landing page color?

I don't have a preference on this, to be honest. @trappmartin and @cpfiffer are better people to ask.

**Comment by cpfiffer** [comment]
I mean, I would prefer white, because I quite like the logo and I don't think it looks good with a color behind it. 

If people don't agree with me (that's fine, not everyone loves white backgrounds) I think the current light blue looks pretty good. If the background is blue, the text in the nav bar should probably also be black, and we should remove the small logo next to "Turing.jl".

**Comment by trappmartin** [comment]
I would prefer colour. :P I think it would be really good to stick to the colour palette Hong linked to. Maybe you could make the nav-bar dark? Similar to the look at the cam.ac.uk site? And use white bold fonts instead? I'm really not an expert on web design thought, but keeping it reasonably close (in terms of colour) to Cambridge guidelines is probably the best idea.

Also I'm with Cameron to remove the small logo in the nav-bar.

**Comment by gold-developer** [comment]
image
@yebai , @trappmartin , @cpfiffer , please take a look at this image and give me advise.

**Comment by gold-developer** [comment]
image
Here, it looks 3 same images, so repetitive.
Removing nav-bar image or new logo would be fine at this point.

**Comment by trappmartin** [comment]
I think it might look better if only the nav bar has a dark colour. I agree, I think we probably only need the main logo (big one) and can drop the rest. What do you think?

**Comment by gold-developer** [comment]
@yebai , folding is working. you can check it now.

**Comment by yebai** [comment]
> @yebai , folding is working. you can check it now.

Indeed - thanks!

> I think it might look better if only the nav bar has a dark colour. I agree, I think we probably only need the main logo (big one) and can drop the rest. What do you think?


Sounds good to drop the small logo in the navbar, and try a black colour for the nav bar.

**Comment by gold-developer** [comment]
@trappmartin , take a look at this url.

https://gold-developer.github.io/turing-docs/

**Comment by gold-developer** [comment]
@yebai , just updated some materials.

**Comment by yebai** [comment]
The new version still looks a bit weird on extra widescreen with Chrome. See below for a screenshot. 

Screenshot 2019-07-23 at 21 14 51

**Comment by trappmartin** [comment]
1. The colours look already much better to me. Would it be possible to use the light blue you had before only for the background of the header and keep the dark background for the nav bar. Would this look good?

2. The text colour of the top button is still black, maybe changes this to white?

Thanks for the efforts so far!

**Comment by trappmartin** [comment]
@gold-developer could you please also change the link to discourse by point to https://discourse.julialang.org/c/domain/probprog instead. 

Thanks!

**Comment by gold-developer** [comment]
@trappmartin please take a look at this and give me advise.

https://gold-developer.github.io/turing-docs/

**Comment by gold-developer** [comment]
@yebai , updated splash page here https://gold-developer.github.io/turing-docs/

**Comment by trappmartin** [comment]
As I said, I would 

1. change the header background colour back to the light blue you once had. Plus black font of course. Nav-bar should stay as is.

2. change the font colour of the top button (appears when scrolling down) to white.

Does that make sense to you?

**Comment by gold-developer** [comment]
@trappmartin , just updated again

**Comment by gold-developer** [comment]
@yebai , @trappmartin , @cpfiffer , please add further requirements.

**Comment by trappmartin** [comment]
The links to the tutorials don’t work because it’s running locally on your account, right? 

I think it looks great!

**Comment by gold-developer** [comment]
> The links to the tutorials don’t work because it’s running locally on your account, right?

I didn't get what you are meaning. could you please let me clear how the links are not working.
Thanks.

**Comment by trappmartin** [comment]
I see. I’m on a mobile device. 

When opening the menu I can only select home -> any of the high level menus like tutorials. Once I click on tutorials I don’t have any menu item to select a tutorial. I can only select tutorials again, but there are no links to actual tutorials. And the link to the introduction tutorial is broken too.

**Comment by gold-developer** [comment]
Omg, let me fix it soon.

**Comment by gold-developer** [comment]
@trappmartin , fixed the issue you just pointed.
Hope it is working well :)

**Comment by trappmartin** [comment]
The menu now works like a charm. But the link on the tutorials homepage is still broken. A `docs` is missing in the URL.

correct URL: `https://gold-developer.github.io/turing-docs/docs/tutorials/0-introduction`
current URL: `https://gold-developer.github.io/turing-docs/tutorials/0-introduction/`

Let me check all the other links...

Link to style-guide is broken too.. on `https://gold-developer.github.io/turing-docs/docs/contributing/guide`

correct URL: `https://gold-developer.github.io/turing-docs/docs/contributing/style-guide`
current URL: `https://gold-developer.github.io/docs/style-guide/`

Link to get-started is broken too.

Could please to through all the links we have on the website and make sure they point to the correct URL?

Thanks!

**Comment by gold-developer** [comment]
@trappmartin , can we chat on skype or google hangouts?
I didn't get where you got the urls, 
Thanks in advance.
hangouts: updev675@gmail.com
skype: live:gold.denis_1

**Comment by trappmartin** [comment]
I'm sorry I'm on the train the whole day. Long ride ahead. I'll take a screenshot to illustrate what I'm talking about. Sorry for the confusion.

**Comment by yebai** [comment]
> When opening the menu I can only select home -> any of the high level menus like tutorials. Once I click on tutorials I don’t have any menu item to select a tutorial. I can only select tutorials again, but there are no links to actual tutorials. And the link to the introduction tutorial is broken too.

A colleague asked why we have 2-level of menus since the first level only has one menu item "Home".  Does it make sense to move all the navigation links to the first-level menu (i.e. the one displaying "menu")? See below for screenshots of first-level and second-level menus. Also, there seems no way to close the menu without clicking on a link. Can we allow the user to close the menu by clicking on the 
"menu" button again?

First-level menu:
Screenshot 2019-07-24 at 13 05 43


Second-level menu:
Screenshot 2019-07-24 at 13 06 05

**Comment by trappmartin** [comment]
The link in the red oval should point to the same address as the link in the red rectangular.
screenshot

The same applies to other links on the webpage.

**Comment by gold-developer** [comment]
@trappmartin , just understood what you have pointed out.
I will check all links. Thanks

**Comment by gold-developer** [comment]
@yebai , @trappmartin , please check it, thanks

**Comment by trappmartin** [comment]
Everything except for the introduction link at the tutorials page works. You probably missed this one. ;)

Once the broken link to the introduction tutorial is fixed, this can be merged.

**Comment by trappmartin** [comment]
Please let me know if you think you cannot  fix the broken link today. I would like to merge the new website asap.

Thanks

**Comment by cpfiffer** [comment]
image

The GitHub button appears to have taken on the color of the splash page, not the color of the nav bar:

**Comment by gold-developer** [comment]
@trappmartin , fixed broken links on the splash page

**Comment by gold-developer** [comment]
@cpfiffer , fixed the issue,

**Comment by gold-developer** [comment]
@yebai , please check the mobile navbar.

**Comment by yebai** [comment]
> @yebai , please check the mobile navbar.

It looks great now. The only remaining TODO items for this PR are

- Merge `docs/pages` and `docs/_docs` in this PR into `docs/src` to facilitate `Documenter.jl`?
- Update the `docs/make.jl` script to automatically generate  [`docs/_docs/library/api.md`](https://github.com/TuringLang/Turing.jl/blob/hg/docs-redesign/docs/_docs/library/api.md).


Maybe we can merge this PR and address the remaining items in a separate PR?

**Comment by yebai** [comment]
@gold-developer I temporarily disabled `https` since it does not load the page correctly. See https://turing.ml/

**Pull request merged**
