### PR TITLE
Add keyword n_tries to maximum_likelihood and maximum_a_posteriori

### PR DESCRIPTION
**Pull request by itsdfish**
This PR adds a keyword `n_tries` to run `maximum_likelihood` and `maximum_a_posteriori` from multiple starting points to mitigate problems with local maxima (see #2279). I added two unit tests and updated the doc strings. Please let me know if there are any edits you would like me to make.

### CODE REVIEW

**Comment by devmotion** [comment]
Generally, if local minima/maxima are problematic - wouldn't it be better to adjust the optimization method (if possible) or turn to global optimization methods? Or use a less naive multi-start optimization method such as MultistartOptimization.jl (https://docs.sciml.ai/Optimization/stable/optimization_packages/multistartoptimization/)? I'm a bit worried that exposing the functionality in the PR in an official API might make it easier for users to miss these potentially better alternatives.

**Comment by itsdfish** [comment]
I was not aware of `MultistartOptimization`. In that case, it would be better to use that and disregard the PR.

**Comment by mhauru** [comment]
Thanks @devmotion, that looks handy; Sorry @itsdfish that I wasn't aware of that when we talked about this.

We could still use the test case you wrote just to check that MultistartOptimization solves it. Or alternatively use your example in the docs. I feel like this is not going to be the last time local maxima come up, and would be handy to have some code to point at and say "you could try doing this".

**Comment by itsdfish** [comment]
@mhauru, no worries! It looks like at least 3 people were unaware of `MultistartOptimization`.  Let me know if you would like me to reporpose  this PR as a test for `MultistartOptimization`. I can update later this week.

**Comment by mhauru** [comment]
If you have the time, I'd be happy to merge an extra test on a model that requires multistart to find the optimum. Might convert it into a paragraph in the docs later.

**Pull request closed without merging**
