### PR TITLE
Bump Optimization to v4, and related packages accordingly

### PR DESCRIPTION
**Pull request by penelopeysm**
Re-opening #2327.

Closes #2348

Closes #2349 

Closes #2350

Closes #2351 

Closes #2352 

Closes #2353

### CODE REVIEW

**Comment by penelopeysm** [comment]
Failing test MWE

```julia
using Random
using Turing
import ReverseDiff

@model function f()
    x ~ Normal(0, 1)
end

Random.seed!(222)

cons(res, x, _) = (res .= [x[1]])
cons_args = (cons=cons, lcons=[0], ucons=[Inf])
initial_params = [0.5, -1.0]

m1 = Turing.Optimisation.estimate_mode(
    f(), MAP(); initial_params=initial_params, cons_args...
)
```

```
ERROR: MethodError: promote_rule(::Type{IrrationalConstants.Log2π}, ::Type{ForwardDiff.Dual{ForwardDiff.Tag{DifferentiationInterfaceForwardDiffExt.ForwardDiffOverSomethingHVPWrapper{OptimizationBase.var"#_f#22"{SciMLBase.OptimizationFunction{true, AutoForwardDiff{nothing, Nothing}, LogDensityFunction{DynamicPPL.TypedVarInfo{@NamedTuple{x::DynamicPPL.Metadata{Dict{AbstractPPL.VarName{:x, typeof(identity)}, Int64}, Vector{Normal{Float64}}, Vector{AbstractPPL.VarName{:x, typeof(identity)}}, Vector{Float64}, Vector{Set{DynamicPPL.Selector}}}}, Float64}, DynamicPPL.Model{typeof(f), (), (), (), Tuple{}, Tuple{}, DynamicPPL.DefaultContext}, Turing.Optimisation.OptimizationContext{DynamicPPL.DefaultContext}}, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(cons), Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}}}, Float64}, Float64, 1}}) is ambiguous.

Candidates:
  promote_rule(::Type{S}, ::Type{T}) where {S<:AbstractIrrational, T<:Number}
    @ Base irrationals.jl:45
  promote_rule(::Type{<:AbstractIrrational}, ::Type{T}) where T<:Real
    @ Base irrationals.jl:44
  promote_rule(::Type{R}, ::Type{ForwardDiff.Dual{T, V, N}}) where {R<:Real, T, V, N}
    @ ForwardDiff ~/.julia/packages/ForwardDiff/PcZ48/src/dual.jl:427

Possible fix, define
  promote_rule(::Type{R}, ::Type{ForwardDiff.Dual{T, V, N}}) where {R<:AbstractIrrational, T, V, N}

Stacktrace:
  [1] promote_type(::Type{IrrationalConstants.Log2π}, ::Type{ForwardDiff.Dual{ForwardDiff.Tag{…}, Float64, 1}})
    @ Base ./promotion.jl:313
  [2] promote_type(::Type, ::Type, ::Type)
    @ Base ./promotion.jl:299
  [3] ForwardOptimize
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/macros.jl:122 [inlined]
  [4] +
    @ ~/.julia/packages/ReverseDiff/p1MzG/src/derivatives/scalars.jl:17 [inlined]
  [5] normlogpdf(z::ReverseDiff.TrackedReal{ForwardDiff.Dual{…}, ForwardDiff.Dual{…}, Nothing})
    @ StatsFuns ~/.julia/packages/StatsFuns/NSRpu/src/distrs/norm.jl:29
  [6] normlogpdf(μ::Float64, σ::Float64, x::ReverseDiff.TrackedReal{…})
    @ StatsFuns ~/.julia/packages/StatsFuns/NSRpu/src/distrs/norm.jl:41
  [7] logpdf(d::Normal{…}, x::ReverseDiff.TrackedReal{…})
    @ Distributions ~/.julia/packages/Distributions/uuqsE/src/univariates.jl:645
  [8] tilde_assume(ctx::Turing.Optimisation.OptimizationContext{…}, dist::Normal{…}, vn::AbstractPPL.VarName{…}, vi::DynamicPPL.TypedVarInfo{…})
    @ Turing.Optimisation ~/ppl/lib/src/optimisation/Optimisation.jl:71
  [9] tilde_assume!!(context::Turing.Optimisation.OptimizationContext{…}, right::Normal{…}, vn::AbstractPPL.VarName{…}, vi::DynamicPPL.TypedVarInfo{…})
    @ DynamicPPL ~/.julia/packages/DynamicPPL/DvdZw/src/context_implementations.jl:144
 [10] macro expansion
    @ ~/.julia/packages/DynamicPPL/DvdZw/src/compiler.jl:579 [inlined]
 [11] f(__model__::DynamicPPL.Model{…}, __varinfo__::DynamicPPL.TypedVarInfo{…}, __context__::Turing.Optimisation.OptimizationContext{…})
    @ Main ./REPL[13]:1
 [12] _evaluate!!(model::DynamicPPL.Model{…}, varinfo::DynamicPPL.TypedVarInfo{…}, context::Turing.Optimisation.OptimizationContext{…})
    @ DynamicPPL ~/.julia/packages/DynamicPPL/DvdZw/src/model.jl:973
 [13] evaluate_threadunsafe!!(model::DynamicPPL.Model{…}, varinfo::DynamicPPL.TypedVarInfo{…}, context::Turing.Optimisation.OptimizationContext{…})
    @ DynamicPPL ~/.julia/packages/DynamicPPL/DvdZw/src/model.jl:946
 [14] evaluate!!(model::DynamicPPL.Model{…}, varinfo::DynamicPPL.TypedVarInfo{…}, context::Turing.Optimisation.OptimizationContext{…})
    @ DynamicPPL ~/.julia/packages/DynamicPPL/DvdZw/src/model.jl:894
 [15] (::LogDensityFunction{…})(z::ReverseDiff.TrackedArray{…})
    @ Turing.Optimisation ~/ppl/lib/src/optimisation/Optimisation.jl:145
 [16] (::LogDensityFunction{…})(z::ReverseDiff.TrackedArray{…}, ::SciMLBase.NullParameters)
    @ Turing.Optimisation ~/ppl/lib/src/optimisation/Optimisation.jl:150
 [17] (::SciMLBase.OptimizationFunction{…})(::ReverseDiff.TrackedArray{…}, ::Vararg{…})
    @ SciMLBase ~/.julia/packages/SciMLBase/DXnzJ/src/scimlfunctions.jl:3812
 [18] (::OptimizationBase.var"#_f#22"{…})(θ::ReverseDiff.TrackedArray{…})
    @ OptimizationBase ~/.julia/packages/OptimizationBase/3r1wm/src/OptimizationDIExt.jl:36
 [19] ReverseDiff.GradientTape(f::OptimizationBase.var"#_f#22"{…}, input::Vector{…}, cfg::ReverseDiff.GradientConfig{…})
    @ ReverseDiff ~/.julia/packages/ReverseDiff/p1MzG/src/api/tape.jl:199
 [20] ReverseDiff.GradientTape(f::Function, input::Vector{ForwardDiff.Dual{ForwardDiff.Tag{…}, Float64, 1}})
    @ ReverseDiff ~/.julia/packages/ReverseDiff/p1MzG/src/api/tape.jl:198
 [21] prepare_gradient(f::Function, ::AutoReverseDiff{false}, x::Vector{ForwardDiff.Dual{ForwardDiff.Tag{…}, Float64, 1}})
    @ DifferentiationInterfaceReverseDiffExt ~/.julia/packages/DifferentiationInterface/FTGtS/ext/DifferentiationInterfaceReverseDiffExt/onearg.jl:53
 [22] prepare_hvp(f::OptimizationBase.var"#_f#22"{…}, backend::DifferentiationInterface.SecondOrder{…}, x::Vector{…}, tx::DifferentiationInterface.Tangents{…})
    @ DifferentiationInterfaceForwardDiffExt ~/.julia/packages/DifferentiationInterface/FTGtS/ext/DifferentiationInterfaceForwardDiffExt/secondorder.jl:35
 [23] prepare_hessian(f::OptimizationBase.var"#_f#22"{…}, backend::DifferentiationInterface.SecondOrder{…}, x::Vector{…})
    @ DifferentiationInterface ~/.julia/packages/DifferentiationInterface/FTGtS/src/second_order/hessian.jl:68
 [24] instantiate_function(f::SciMLBase.OptimizationFunction{…}, x::Vector{…}, adtype::AutoForwardDiff{…}, p::SciMLBase.NullParameters, num_cons::Int64; g::Bool, h::Bool, hv::Bool, fg::Bool, fgh::Bool, cons_j::Bool, cons_vjp::Bool, cons_jvp::Bool, cons_h::Bool, lag_h::Bool)
    @ OptimizationBase ~/.julia/packages/OptimizationBase/3r1wm/src/OptimizationDIExt.jl:82
 [25] instantiate_function
    @ ~/.julia/packages/OptimizationBase/3r1wm/src/OptimizationDIExt.jl:28 [inlined]
 [26] #instantiate_function#48
    @ ~/.julia/packages/OptimizationBase/3r1wm/src/OptimizationDIExt.jl:294 [inlined]
 [27] instantiate_function
    @ ~/.julia/packages/OptimizationBase/3r1wm/src/OptimizationDIExt.jl:287 [inlined]
 [28] OptimizationBase.OptimizationCache(prob::SciMLBase.OptimizationProblem{…}, opt::Optim.IPNewton{…}; callback::Function, maxiters::Nothing, maxtime::Nothing, abstol::Nothing, reltol::Nothing, progress::Bool, structural_analysis::Bool, manifold::Nothing, kwargs::@Kwargs{})
    @ OptimizationBase ~/.julia/packages/OptimizationBase/3r1wm/src/cache.jl:37
 [29] OptimizationCache
    @ ~/.julia/packages/OptimizationBase/3r1wm/src/cache.jl:25 [inlined]
 [30] #__init#2
    @ ~/.julia/packages/OptimizationOptimJL/BIkTp/src/OptimizationOptimJL.jl:109 [inlined]
 [31] __init
    @ ~/.julia/packages/OptimizationOptimJL/BIkTp/src/OptimizationOptimJL.jl:80 [inlined]
 [32] #init#657
    @ ~/.julia/packages/SciMLBase/DXnzJ/src/solve.jl:174 [inlined]
 [33] init
    @ ~/.julia/packages/SciMLBase/DXnzJ/src/solve.jl:172 [inlined]
 [34] solve(::SciMLBase.OptimizationProblem{…}, ::Optim.IPNewton{…}; kwargs::@Kwargs{})
    @ SciMLBase ~/.julia/packages/SciMLBase/DXnzJ/src/solve.jl:96
 [35] solve(::SciMLBase.OptimizationProblem{…}, ::Optim.IPNewton{…})
    @ SciMLBase ~/.julia/packages/SciMLBase/DXnzJ/src/solve.jl:93
 [36] estimate_mode(model::DynamicPPL.Model{…}, estimator::MAP, solver::Nothing; initial_params::Vector{…}, adtype::AutoForwardDiff{…}, cons::Function, lcons::Vector{…}, ucons::Vector{…}, lb::Nothing, ub::Nothing, kwargs::@Kwargs{})
    @ Turing.Optimisation ~/ppl/lib/src/optimisation/Optimisation.jl:499
 [37] estimate_mode
    @ ~/ppl/lib/src/optimisation/Optimisation.jl:456 [inlined]
 [38] top-level scope
    @ REPL[18]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by penelopeysm** [comment]
This method ambiguity is fixed in https://github.com/JuliaDiff/ForwardDiff.jl/pull/687, it just needs a release

**Comment by penelopeysm** [comment]
I think bumping Optimization to v4 would also allow it to work with Mooncake as an AD backend (since it now goes via DifferentiationInterface).

**Comment by penelopeysm** [comment]
@yebai can do!

**Comment by penelopeysm** [comment]
It's curious, but the ForwardDiff tests that were failing previously seem to have been fixed on Julia 1.11.

These were the previous failures: https://github.com/TuringLang/Turing.jl/actions/runs/11072371830/job/30766467971 This was pre-1.11 so the CI was running on 1.10.5.

In contrast, none of those tests fail here: https://github.com/TuringLang/Turing.jl/actions/runs/11483911558/job/31960475967 The only failure here is because Mooncake was marked as broken, which it isn't.

There were some changes to promote_rule recently, https://github.com/JuliaLang/julia/commits/6c70bf784999b478bc176fe594738f9746a1dcfd/base/irrationals.jl so maybe one of them fixed it for us.

**Comment by penelopeysm** [comment]
The remaining test failure is #2371. I could rerun it to get the green tick, but don't see much of a point.

**Review by mhauru — APPROVED** [review]
Looks good!

**Pull request merged**
