### PR TITLE
Get ready for AHMC v0.2.0

### PR DESCRIPTION
**Pull request by xukai92**
AHMC now assumes the grad function to return a val-grad tuple.

### CODE REVIEW

**Comment by xukai92** [comment]
Please don't merge until AHMC v0.2.0 is there.

**Comment by xukai92** [comment]
Mainly just updated the gradient function that passes to AHMC to return both value and gradient, plus also passing `progress` keyword argument to AHMC.

**Comment by xukai92** [comment]
There are many tests failed but I'm not quite sure which ones are known to fail? (Should we actually mark them as known to fail by `@test_broken`

**Comment by xukai92** [comment]
There seems to be something wrong - one of the `hmc.jl` test fails. I'm looking into it.

**Comment by yebai** [comment]
> There seems to be something wrong - one of the hmc.jl test fails. I'm looking into it.

I think we'd better make a new release of Turing to accommodate AHMC 0.2. I'll take a look at the new AHMC PR today.

**Pull request merged**
