### PR TITLE
Update Turing to AbstractMCMC 1.0, AdvancedMH 0.5, and DynamicPPL 0.6

### PR DESCRIPTION
**Pull request by devmotion**
Make Turing compatible with all the new and [upcoming](https://github.com/TuringLang/DynamicPPL.jl/issues/73) releases.

Tests will fail until a new version of DynamicPPL is released.

### CODE REVIEW

**Comment by devmotion** [comment]
I haven't updated the compiler docs yet, I thought we might want to do that separately in a more coordinated fashion (see https://github.com/TuringLang/DynamicPPL.jl/issues/65).

**Comment by mohamed82008** [comment]
Let's also bump DistributionsAD to 0.5.

**Comment by mohamed82008** [comment]
@torfjelde should we wait on this update until we sort out Bijectors then bump DAD and Bijectors versions as well? I think the new DAD-Bijectors versions will be technically breaking as the behavior of AD and bijectors AD will change.

**Comment by mohamed82008** [comment]
By "wait", I mean not to release Turing yet. But we can merge the PR.

**Comment by mohamed82008** [comment]
DPPL 0.6 is released.

**Comment by devmotion** [comment]
So we update DistributionsAD in a separate PR?

**Comment by mohamed82008** [comment]
> So we update DistributionsAD in a separate PR?

Yes

**Pull request merged**
