### PR TITLE
Remove state-saving by default

### PR DESCRIPTION
**Pull request by cpfiffer**
Hotfix for #1091 and reports [here](https://discourse.julialang.org/t/how-to-solve-error-while-running-parallel-sampling-in-julia-with-turing-and-distributed-package/34551/3). This PR makes it so that state is not automatically saved in a `Chains` object when sampling is completed -- people who want to resume the chain will have to explicitly plan ahead of time to resume sampling:

```julia
chain = sample(model, spl, N; save_state = true)
```

### CODE REVIEW

**Comment by mohamed82008** [comment]
Please change `prob"x = 1.0, y = 1.0 | chain = chain"` to `prob"x = 1.0, y = 1.0 | chain = chain, model = gdemo"` in the docs, the guide.md file.

**Comment by mohamed82008** [comment]
Or add both saying a word about the `save_state` kwarg.

**Comment by yebai** [comment]
@cpfiffer can you take a look at Mohamed's comment, and see whether we can fix them before merging?

**Comment by yebai** [comment]
> Hi @yebai, I just got a benchmark command from you,
> But I can't determine on which branches to run,
> Please specify the branches in your command.

@KDr2 Maybe reduce unnecessary replies (e.g. only reply to comments containing `@BayesBot benchmark()`  from the Benchmark bot?

**Comment by cpfiffer** [comment]
This should be good to merge once the tests pass.

**Comment by KDr2** [comment]
> > Hi @yebai, I just got a benchmark command from you,
> > But I can't determine on which branches to run,
> > Please specify the branches in your command.
> 
> @KDr2 Maybe reduce unnecessary replies (e.g. only reply to comments containing `@BayesBot benchmark()` from the Benchmark bot?

OK :D

**Pull request merged**
