### PR TITLE
Add a pre-commit config

### PR DESCRIPTION
**Pull request by mhauru**
[pre-commit](https://pre-commit.com/) is a tool that sets up git pre-commit hooks for you and makes it easy to run them. I added a simple config that checks for basic things like trailing whitespace and invalid TOML files, and runs JuliaFormatter. You can run it on demand with `pre-commit run` or `pre-commit run --all-files`, or run `pre-commit install` and from there on it'll run every time you try to `git commit`. You do need to install pre-commit through means other than Julia's package manager, such as homebrew, apt, or pip. I _think_ it's cross-platform, but I've never tried it on Windows.

I'll use this myself. Whether it should be in the repo I think depends on whether others want to use it as well, hence this draft PR for discussing. I'm not offended in the slightest if others aren't interested, but figured I would offer this in case it's seen as useful.

### CODE REVIEW

**Comment by torfjelde** [comment]
As mentioned in another comment, I'm not a fan of this :confused: 
https://github.com/TuringLang/Turing.jl/issues/2241#issuecomment-2153075245

**Comment by devmotion** [comment]
Seconded: https://github.com/TuringLang/Turing.jl/issues/2241#issuecomment-2153395963

**Comment by mhauru** [comment]
No problem, I'll close. If anyone ever wants a pre-commit config for themselves I'll point them here.

**Comment by penelopeysm** [comment]
Running JuliaFormatter the usual way can be annoyingly slow. It's possible to substantially speed it up by following the instructions in this comment https://github.com/domluna/JuliaFormatter.jl/issues/633#issuecomment-1518805248 to build a sysimage and re-use it upon formatting.

On DynamicPPL, this runs in 0.3 s compared to 4.5 s for the naive `julia -e "..."`.

My corresponding `.pre-commit-config.yaml` is

```yaml
repos:
- repo: local
  hooks:
  - id: format
    name: format
    language: system
    entry: bash -c 'source ~/.bash_profile; jformat'
```

(some tweaks may be needed depending on your shell and config setup etc)

**Pull request closed without merging**
