### PR TITLE
Docs Versioning Support

### PR DESCRIPTION
**Pull request by KDr2**
See https://github.com/TuringLang/Turing.jl/issues/837.

Ready to merge.

### CODE REVIEW

**Comment by yebai** [comment]
Thanks, @KDr2! I cloned the repo so that we can preview the changes. The live preview can be found at https://yebai.github.io/Turing.jl/dev/

It appears that

- https://yebai.github.io/Turing.jl/ is broken.
- Some css files can not be loaded due to path issues.

**Comment by KDr2** [comment]
Hi @yebai the error is caused by the context path (i.e. the base url).

The baseurl is set while compiling pages with Jekyll. for the dev version, it's `/dev`, for the tagged version, it's `/vN.M`.

In your case, the baseurl is `/Turing.jl/dev/`, not `/dev`. You can create a new CNAME record, for example, `testing.turing.ml` to test it.

**Comment by KDr2** [comment]
@yebai I've found the paths issues were caused by a glitch of Jekyll's `baseurl` on Travis ENV. It is fixed now.

I set up a test site, on my forked repo:
- https://github.com/KDr2/Turing.jl
- https://gp.rev.red

Please have a look.

**Comment by yebai** [comment]
Thanks, @KDr2. It looks good to me except that the dropdown menu for version switch is empty. It might be tricky to include old versions of doc since they are based on a different template, but maybe includes the last release (i.e. `v0.6.23`, which is based on the new template) together with `dev`?

**Comment by cpfiffer** [comment]
I might also change the font size of the class `md-header-nav__source` to 1.4rem instead of 1rem, because it's a very small dropdown.

**Comment by KDr2** [comment]
>  includes the last release (i.e. `v0.6.23`, which is based on the new template) together with `dev`?

Done, please check:
- https://gp.rev.red
- https://github.com/TuringLang/Turing.jl/tree/gh-pages

**Pull request merged**
