### PR TITLE
Fix for HMCs `dot_assume`

### PR DESCRIPTION
**Pull request by torfjelde**
Currently `dot_assume` for HMC is broken, which this PR fixes.

This case is covered by tests, but (AFAIK) only in DynamicPPL's integration tests, _not_ in Turing's tests.

Should I copy-paste these or is there a way we can just run the integration tests from DPPL with this Turing version?

### CODE REVIEW

**Comment by devmotion** [comment]
> Should I copy-paste these or is there a way we can just run the integration tests from DPPL with this Turing version?

I think the test setup is simpler and more reliable if you just copy the tests (I guess we could use the test models but probably that's what's done already in DynamicPPL?).

**Comment by torfjelde** [comment]
Eeeh weird. I can't reproduce the errors locally :flushed:

**Comment by torfjelde** [comment]
Aaaaight so I finally figured out what's going wrong:

``` julia
julia> using Tracker, Distributions

julia> m = first(param(zeros(1)))
0.0 (tracked)

julia> s = first(param(ones(1)))
1.0 (tracked)

julia> typeof(Normal.(m, s))
Tracker.Tracked{Normal{Float64}}
```

And DistributionsAD.jl doesn't address this issue:

``` julia
julia> using DistributionsAD

julia> typeof(Normal.(m, s))
Tracker.Tracked{Normal{Float64}}
```

It comes down to Tracker not handling `broadcast` properly. I'm just going to mark this test as broken for now (don't think anyone uses Tracker with Turing anyways) and raise an issue over at Tracker.jl.

**Comment by devmotion** [comment]
Maybe related to or even the same as https://github.com/FluxML/Tracker.jl/issues/65?

**Comment by torfjelde** [comment]
Possibly! I've made a new issue as it's not completely obvious to me whether it's the same or not atm: https://github.com/FluxML/Tracker.jl/issues/119

**Comment by torfjelde** [comment]
Now running into https://github.com/TuringLang/Turing.jl/issues/1756

**Comment by torfjelde** [comment]
Renamed `Core` to `TuringCore`. Should we maybe bump the minor version? Seems like this could break people's code (e.g. I know lots of my snippets will break).

**Comment by torfjelde** [comment]
This should be good to go once #1762 has gone through :+1:

**Review by cpfiffer — APPROVED** [review]

**Pull request merged**
