### PR TITLE
WIP: support Julia 1.0

### PR DESCRIPTION
**Pull request by yebai**
This is still a work in progress. Perhaps we can move the work to master now?

Related issue: https://github.com/TuringLang/Turing.jl/issues/462

### CODE REVIEW

**Comment by xukai92** [comment]
I think we should at least have PG & Gibbs tested before merging into master. Otherwise half of the functionality of Turing is down. Also this branch currently depends on TuringLang/Chain, which is not registered yet. I don't what will happen when a user checking into the master and trying to run some inference.

**Comment by trappmartin** [comment]
I agree with Kai and think we should also fix the dependency issue with Chain at first, it is currently not registered which is a breaking issue.

**Comment by yebai** [comment]
Sure, let's fix remaining issues before merging into master. 

@trappmartin can you quickly get Chain registered, please? 

@xukai92 could you take a look at why PG/SMC is still broken, please?

**Comment by trappmartin** [comment]
With the old package manager this is not possible. I’m not sure about the new one. 

It might be good to port the necessary tests from Mamba to Chain so that we can at least unit test Chain.

**Comment by yebai** [comment]
I fixed some complaints related to missing `take!` function today. This is likely introduced in early attempts at fixing task copying. Now the code compiles and run. However, there are likely further compiler bugs since running the following code would halt

```julia
julia> @model gdemo(x) = begin
         s ~ InverseGamma(2,3)
         m ~ Normal(0,sqrt(s))
         x[1] ~ Normal(m, sqrt(s))
         x[2] ~ Normal(m, sqrt(s))
         return s, m
       end

gdemo (generic function with 2 methods)

julia> #  Run sampler, collect results
       c1 = sample(gdemo([1.5, 2]), SMC(1000))
[Turing]:  Assume - `s` is a parameter
 @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:78
[Turing]:  Assume - `m` is a parameter
 @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:78
[Turing]:  Observe - `x` is an observation
 @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:59
``` 

Note the print message `@~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:59` might lead us to the cause -- Julia 1.0 inserts LineNumberNode in a different way compared to 0.6. This might cause the compiler broken down.

**Comment by xukai92** [comment]
> Note the print message @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:59 might lead us to the cause -- Julia 1.0 inserts LineNumberNode in a different way compared to 0.6. This might cause the compiler broken.

It might cause problem as I don't know what exactly the `::LineNumberNode` is used for. But as long as the HMC sampler works, the compiler should be fine? Or you mean there might be some issues related to `marco` used in coroutine?

**Comment by yebai** [comment]
> It might cause problem as I don't know what exactly the ::LineNumberNode is used for. But as long as the HMC sampler works, the compiler should be fine? Or you mean there might be some issues related to marco used in coroutine?

The issue might be in the `assume` / `observe` macro. HMC might escape from this issue since it does not involve `resampling`.  Just my first intuition!

**Comment by xukai92** [comment]
I see. I think this should be resolved more easily if our debugging `dprintln` is good. Maybe we can take this chance also resolve the logging issue proposed in one of the meeting. How about creating an issue on this and re-write all logging for debugging using https://docs.julialang.org/en/v0.7.0/stdlib/Logging/
OFC I can take care of this part

**Comment by yebai** [comment]
> How about creating an issue on this and re-write all logging for debugging using https://docs.julialang.org/en/v0.7.0/stdlib/Logging/

Sounds great!

**Comment by willtebbutt** [comment]
> How about creating an issue on this and re-write all logging for debugging using https://docs.julialang.org/en/v0.7.0/stdlib/Logging/

I would suggest looking at Invenia's [Memento.jl](https://github.com/invenia/Memento.jl). From what I understand it is substantially more feature-ful than the stdlib logging library, and Invenia are committed to maintaining it.

**Comment by xukai92** [comment]
```
WARNING: eval from module Plots to MCMCChain:    
Expr(:call, Expr(:., :Sys, :(:islinux)))
  ** incremental compilation may be broken for this module **

WARNING: eval from module Plots to MCMCChain:    
Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1368 =#, Expr(:call, Expr(:., :Sys, :(:isapple))))
  ** incremental compilation may be broken for this module **

WARNING: eval from module Plots to MCMCChain:    
Expr(:function, Expr(:call, :_show, Expr(:::, :io, :IO), Expr(:::, Expr(:curly, :MIME, Expr(:call, :Symbol, "application/postscript"))), Expr(:::, :plt, Expr(:curly, :Plot, :GRBackend))), Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1379 =#, Expr(:call, Expr(:., :GR, :(:emergencyclosegks))), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1380 =#, :filepath = Expr(:call, :*, Expr(:call, :tempname), ".", "ps"), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1381 =#, :env = Expr(:call, :get, :ENV, "GKSwstype", "0"), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1382 =#, Expr(:ref, :ENV, "GKSwstype") = "ps", #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1383 =#, Expr(:ref, :ENV, "GKS_FILEPATH") = :filepath, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1384 =#, Expr(:call, :gr_display, :plt, "ps"), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1385 =#, Expr(:call, Expr(:., :GR, :(:emergencyclosegks))), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1386 =#, Expr(:call, :write, :io, Expr(:call, :read, :filepath, :String)), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1387 =#, Expr(:call, :rm, :filepath), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1388 =#, Expr(:if, Expr(:call, :!=, :env, "0"), Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1389 =#, Expr(:ref, :ENV, "GKSwstype") = :env), Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1391 =#, Expr(:call, :pop!, :ENV, "GKSwstype")))))
  ** incremental compilation may be broken for this module **

WARNING: eval from module Plots to MCMCChain:    
Expr(:function, Expr(:call, :_show, Expr(:::, :io, :IO), Expr(:::, Expr(:curly, :MIME, Expr(:call, :Symbol, "application/pdf"))), Expr(:::, :plt, Expr(:curly, :Plot, :GRBackend))), Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1379 =#, Expr(:call, Expr(:., :GR, :(:emergencyclosegks))), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1380 =#, :filepath = Expr(:call, :*, Expr(:call, :tempname), ".", "pdf"), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1381 =#, :env = Expr(:call, :get, :ENV, "GKSwstype", "0"), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1382 =#, Expr(:ref, :ENV, "GKSwstype") = "pdf", #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1383 =#, Expr(:ref, :ENV, "GKS_FILEPATH") = :filepath, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1384 =#, Expr(:call, :gr_display, :plt, "pdf"), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1385 =#, Expr(:call, Expr(:., :GR, :(:emergencyclosegks))), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1386 =#, Expr(:call, :write, :io, Expr(:call, :read, :filepath, :String)), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1387 =#, Expr(:call, :rm, :filepath), #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1388 =#, Expr(:if, Expr(:call, :!=, :env, "0"), Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1389 =#, Expr(:ref, :ENV, "GKSwstype") = :env), Expr(:block, #= Symbol("/Users/kai/.julia/packages/Plots/3Nsmt/src/backends/gr.jl"):1391 =#, Expr(:call, :pop!, :ENV, "GKSwstype")))))
  ** incremental compilation may be broken for this module **
...
[Turing]: AD chunk size is set as 40
[Turing]:  Assume - `s` is a parameter
 @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:78
[Turing]:  Assume - `m` is a parameter
 @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:78
[Turing]:  Observe - `x` is an observation
 @~(::LineNumberNode, ::Module, ::Any, ::Any) at compiler.jl:59
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type{T} where T, got=T0<:Real)
rec_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/stackwalk.c:94
record_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:246 [inlined]
jl_throw at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:577
jl_type_error_rt at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:118
jl_type_error at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:124
jl_f_issubtype at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:415
typeof_tfunc at ./compiler/tfuncs.jl:393
typeof_tfunc at ./compiler/tfuncs.jl:391
typeof_tfunc at ./compiler/tfuncs.jl:396
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
builtin_tfunction at ./compiler/tfuncs.jl:1170
builtin_tfunction at ./compiler/tfuncs.jl:1079
abstract_call at ./compiler/abstractinterpretation.jl:551
abstract_eval_call at ./compiler/abstractinterpretation.jl:798
abstract_eval at ./compiler/abstractinterpretation.jl:883
typeinf_local at ./compiler/abstractinterpretation.jl:1107
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1163
typeinf at ./compiler/typeinfer.jl:15
typeinf_edge at ./compiler/typeinfer.jl:492
abstract_call_method at ./compiler/abstractinterpretation.jl:321
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:81
abstract_call at ./compiler/abstractinterpretation.jl:769
abstract_eval_call at ./compiler/abstractinterpretation.jl:798
abstract_eval at ./compiler/abstractinterpretation.jl:883
typeinf_local at ./compiler/abstractinterpretation.jl:1107
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1163
typeinf at ./compiler/typeinfer.jl:15
typeinf_edge at ./compiler/typeinfer.jl:492
abstract_call_method at ./compiler/abstractinterpretation.jl:321
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:81
abstract_call at ./compiler/abstractinterpretation.jl:769
abstract_apply at ./compiler/abstractinterpretation.jl:477
abstract_call at ./compiler/abstractinterpretation.jl:525
abstract_eval_call at ./compiler/abstractinterpretation.jl:798
abstract_eval at ./compiler/abstractinterpretation.jl:883
typeinf_local at ./compiler/abstractinterpretation.jl:1107
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1163
...
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:841
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:865 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:872
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
exec_options at ./client.jl:239
_start at ./client.jl:432
true_main at /Users/kai/bin/julia (unknown line)
main at /Users/kai/bin/julia (unknown line)
┌ Warning: broadcast will default to iterating over its arguments in the future. Wrap arguments of
│ type `x::InverseGamma{Float64}` with `Ref(x)` to ensure they broadcast as "scalar" elements.
│   caller = ip:0x0
└ @ Core :-1
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type{T} where T, got=T0<:Real)
rec_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/stackwalk.c:94
record_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:246 [inlined]
jl_throw at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:577
jl_type_error_rt at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:118
jl_type_error at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:124
jl_f_issubtype at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:415
typeof_tfunc at ./compiler/tfuncs.jl:393
typeof_tfunc at ./compiler/tfuncs.jl:391
typeof_tfunc at ./compiler/tfuncs.jl:396
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
builtin_tfunction at ./compiler/tfuncs.jl:1170
builtin_tfunction at ./compiler/tfuncs.jl:1079
abstract_call at ./compiler/abstractinterpretation.jl:551
abstract_eval_call at ./compiler/abstractinterpretation.jl:798
abstract_eval at ./compiler/abstractinterpretation.jl:883
typeinf_local at ./compiler/abstractinterpretation.jl:1107
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1163
typeinf at ./compiler/typeinfer.jl:15
typeinf_edge at ./compiler/typeinfer.jl:492
abstract_call_method at ./compiler/abstractinterpretation.jl:321
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:81
abstract_call at ./compiler/abstractinterpretation.jl:769
abstract_eval_call at ./compiler/abstractinterpretation.jl:798
abstract_eval at ./compiler/abstractinterpretation.jl:883
typeinf_local at ./compiler/abstractinterpretation.jl:1107
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1163
typeinf at ./compiler/typeinfer.jl:15
typeinf_edge at ./compiler/typeinfer.jl:492
...
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_apply_with_saved_exception_state at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:257
jl_type_infer at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:275
jl_compile_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1784
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1828
##gdemo_model#392 at /Users/kai/.julia/dev/Turing/test/hmc.jl/hmc_reverse_diff.jl:100 [inlined]
##gdemo_model#392 at ./none:0
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
jl_f__apply_latest at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:601
#invokelatest#1 at ./essentials.jl:691 [inlined]
invokelatest at ./essentials.jl:690 [inlined]
#sample#108 at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:121
unknown function (ip: 0x116a4190e)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
sample at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:95
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x131eec2df)
unknown function (ip: 0x1)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:841
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:865 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:872
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
exec_options at ./client.jl:239
...
jfptr_typeinf_ext_1.clone_1 at /Applications/Julia-0.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_apply_with_saved_exception_state at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:257
jl_type_infer at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:275
jl_compile_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1784
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1828
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
jl_f__apply_latest at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:601
#invokelatest#1 at ./essentials.jl:691 [inlined]
invokelatest at ./essentials.jl:690 [inlined]
runmodel at /Users/kai/.julia/dev/Turing/src/samplers/support/hmc_core.jl:98
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
#sample#108 at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:127
unknown function (ip: 0x116a4190e)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
sample at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:95
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x131eec2df)
unknown function (ip: 0x1)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:841
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:865 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:872
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
exec_options at ./client.jl:239
_start at ./client.jl:432
true_main at /Users/kai/bin/julia (unknown line)
main at /Users/kai/bin/julia (unknown line)
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type{T} where T, got=T0<:Real)
rec_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/stackwalk.c:94
record_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:246 [inlined]
jl_throw at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:577
jl_type_error_rt at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:118
jl_type_error at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:124
jl_f_issubtype at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:415
typeof_tfunc at ./compiler/tfuncs.jl:393
typeof_tfunc at ./compiler/tfuncs.jl:391
typeof_tfunc at ./compiler/tfuncs.jl:396
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
builtin_tfunction at ./compiler/tfuncs.jl:1170
...
jfptr_typeinf_ext_1.clone_1 at /Applications/Julia-0.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_apply_with_saved_exception_state at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:257
jl_type_infer at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:275
jl_compile_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1784
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1828
##gdemo_model#392 at /Users/kai/.julia/dev/Turing/test/hmc.jl/hmc_reverse_diff.jl:100 [inlined]
##gdemo_model#392 at ./none:0
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
jl_f__apply_latest at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:601
#invokelatest#1 at ./essentials.jl:691 [inlined]
invokelatest at ./essentials.jl:690 [inlined]
runmodel at /Users/kai/.julia/dev/Turing/src/samplers/support/hmc_core.jl:98
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
#sample#108 at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:127
unknown function (ip: 0x116a4190e)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
sample at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:95
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x131eec2df)
unknown function (ip: 0x1)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:841
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:865 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:872
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
exec_options at ./client.jl:239
_start at ./client.jl:432
true_main at /Users/kai/bin/julia (unknown line)
main at /Users/kai/bin/julia (unknown line)
┌ Warning: Requires now needs a UUID; please see the readme for changes in 0.7.
└ @ Turing ~/.julia/dev/Turing/src/samplers/support/adapt.jl:60
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type{T} where T, got=T0<:Real)
rec_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/stackwalk.c:94
record_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:246 [inlined]
jl_throw at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:577
jl_type_error_rt at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:118
jl_type_error at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:124
...
typeinf at ./compiler/typeinfer.jl:15
typeinf_ext at ./compiler/typeinfer.jl:567
typeinf_ext at ./compiler/typeinfer.jl:604
jfptr_typeinf_ext_1.clone_1 at /Applications/Julia-0.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_apply_with_saved_exception_state at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:257
jl_type_infer at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:275
jl_compile_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1784
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1828
##gdemo_model#392 at /Users/kai/.julia/dev/Turing/test/hmc.jl/hmc_reverse_diff.jl:100 [inlined]
##gdemo_model#392 at ./none:0
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
jl_f__apply_latest at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:601
#invokelatest#1 at ./essentials.jl:691 [inlined]
invokelatest at ./essentials.jl:690 [inlined]
runmodel at /Users/kai/.julia/dev/Turing/src/samplers/support/hmc_core.jl:98
gradient at /Users/kai/.julia/dev/Turing/src/core/ad.jl:71
grad_func at /Users/kai/.julia/dev/Turing/src/samplers/support/hmc_core.jl:14
#_leapfrog#81 at /Users/kai/.julia/dev/Turing/src/samplers/support/hmc_core.jl:136
unknown function (ip: 0x13c0fc4ea)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
#_leapfrog at ./none:0
unknown function (ip: 0x13c0fbdae)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
#_hmc_step#96 at /Users/kai/.julia/dev/Turing/src/samplers/hmcda.jl:165
unknown function (ip: 0x13c0fa547)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
#_hmc_step at ./none:0
unknown function (ip: 0x13c0f9beb)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
step at /Users/kai/.julia/dev/Turing/src/samplers/hmcda.jl:94
unknown function (ip: 0x13c0eddd3)
#sample#108 at ./util.jl:213
unknown function (ip: 0x116a4190e)
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
sample at /Users/kai/.julia/dev/Turing/src/samplers/hmc.jl:95
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
[HMC] Sampling...100% Time: 0:01:47
[HMC] Finished with
  Running time        = 106.45003389999995;
  Accept rate         = 0.9903333333333333;
  #lf / sample        = 9.996666666666666;
  #evals / sample     = 11.987;
  pre-cond. diag mat  = [1.0, 1.0].
┌ Warning: `search(s::AbstractString, t::AbstractString)` is deprecated, use `something(findfirst(t, s), 0:-1)` instead.
│   caller = #49 at io.jl:20 [inlined]
└ @ Core ~/.julia/dev/Turing/src/core/io.jl:20
2.0823135949136375 ≈ 2.0416666666666665?
1.1496691802786985 ≈ 1.1666666666666667?
```

**Comment by xukai92** [comment]
#471 is resolved through f2dba79 to 3d1ea43

**Comment by yebai** [comment]
SMC and PG are working fine now.

**Comment by xukai92** [comment]
As all samplers should work we should aim to make this PR pass all tests.

I'm currently see this test fail on my local
```
Test Failed at /Users/kai/.julia/dev/Turing/test/compiler.jl/observe.jl:21
  Expression: res[:logevidence] ≈ 2 * log(0.5)
   Evaluated: NaN ≈ -1.3862943611198906
ERROR: LoadError: LoadError: There was an error during testing
in expression starting at /Users/kai/.julia/dev/Turing/test/compiler.jl/observe.jl:21
in expression starting at /Users/kai/.julia/dev/Turing/test/runtests.jl:82
```

Have we made any change to the `weight` field of the `Chain`?

**Comment by trappmartin** [comment]
I agree I'm currently fixing tests too. Let's coordinate via slack. 
I don't think we changed the `weight` field of `Chain`.

**Comment by trappmartin** [comment]
Test folders currently failing:

- ad.jl
- compiler.jl
- <s>container.jl</s>
- varinfo.jl
- io.jl
- <s>util.jl</s>
- <s>transform.jl</s>
- <s>resample.jl</s>
- <s>adapt.jl</s>
- <s>sampler.jl</s>
- gibbs.jl
- nuts.jl
- hmcda.jl
- hmc_core.jl
- sghmc.jl
- sgld.jl
- is.jl
- mh.jl
- pmmh.jl
- ipmcmc.jl
- tarray.jl
- <s>taskcopy.jl</s> <-- more test are necessary
- <s>trace.jl</s>

**Comment by yebai** [comment]
All tests should be passing now except #481 and #480 

@xukai92 @hessammehr @trappmartin

**Comment by hessammehr** [comment]
Playing around with it right now and very happy! Thank you for all the hard work folks!

**Comment by trappmartin** [comment]
I'll do some final clean-up of the test-suit. After this, I'm happy to! 😺

**Pull request merged**
