### PR TITLE
Performance tips

### PR DESCRIPTION
**Pull request by trappmartin**
- Add a page on performance tips
- Changes the description of Turing.jl at the splash page

cc: @yebai

### CODE REVIEW

**Comment by trappmartin** [comment]
Thanks for the feedback!

**Comment by trappmartin** [comment]
@mohamed82008 could you provide a full example of using `@code_warntype`.
Should this work?

```julia
using Turing

@model tmodel(x, y) = begin
    p,n = size(x)
    params = Vector{Real}(undef, n)
    for i = 1:n
        params[i] ~ Truncated(Normal(), 0, Inf)
    end

    a = x * params
    y ~ MvNormal(a, 1.0)
end

model = tmodel()

vi = Turing.VarInfo(model)
spl = Turing.SampleFromPrior()
@code_warntype model.f(vi, spl, model)
```

**Comment by mohamed82008** [comment]
This works.

```julia
using Turing

@model tmodel(x, y, ::Type{T} = Float64) where {T} = begin
    p,n = size(x)
    params = Vector{T}(undef, n)
    for i = 1:n
        params[i] ~ Truncated(Normal(), 0, Inf)
    end
    a = x * params
    y ~ MvNormal(a, 1.0)
end

model = tmodel(rand(2,2), rand(2))

varinfo = Turing.VarInfo(model)
spl = Turing.SampleFromPrior()
@code_warntype model.f(varinfo, spl, model)
```

**Comment by xukai92** [comment]
Just copy-and-paste two other tricks from our notion.so

### Use of FillArrys.jl
```julia
using FillArrays

@model AHMCGaussian(y, N) = begin
    mu ~ Normal(0, 1)
    sigma ~ Truncated(Cauchy(0, 5), 0, Inf)
    y ~ MvNormal(Fill(mu, N), sigma)  # use `Fill(mu, N)` is memory freiendly
end
```

### Use of PaddedViews.jl
```julia
using PaddedViews
​
@model AHMCregression(x, y, Nd, Nc) = begin
    B ~ MvNormal(zeros(Nc+1), 10)
    sigma ~ Truncated(Cauchy(0, 5), 0, Inf)
    mu = PaddedView(1, x, (Nd,Nc+1)) * B
    y ~ MvNormal(mu, sigma)
end
```

**Comment by trappmartin** [comment]
> Just copy-and-paste two other tricks from our notion.so
> 
> ### Use of FillArrys.jl
> ```julia
> using FillArrays
> 
> @model AHMCGaussian(y, N) = begin
>     mu ~ Normal(0, 1)
>     sigma ~ Truncated(Cauchy(0, 5), 0, Inf)
>     y ~ MvNormal(Fill(mu, N), sigma)  # use `Fill(mu, N)` is memory freiendly
> end
> ```
> 
> ### Use of PaddedViews.jl
> ```julia
> using PaddedViews
> ​
> @model AHMCregression(x, y, Nd, Nc) = begin
>     B ~ MvNormal(zeros(Nc+1), 10)
>     sigma ~ Truncated(Cauchy(0, 5), 0, Inf)
>     mu = PaddedView(1, x, (Nd,Nc+1)) * B
>     y ~ MvNormal(mu, sigma)
> end
> ```

This doesn't seem to work anymore. Not sure why, but we now get some tracker errors.
So I would rather leave them out for now.

**Comment by trappmartin** [comment]
Should be ready.

**Pull request merged**
