### PR TITLE
Docstring updates, guide improvements.

### PR DESCRIPTION
**Pull request by cpfiffer**
Adds some meager docstrings for the distributions we have, and tacks them onto the API page. I've also changed the name from Library to API for the page that shows off our docstrings.

It doesn't really seem like the docs are being built automatically -- @KDr2 do you know what's up with that?

### CODE REVIEW

**Comment by KDr2** [comment]
Hi @cpfiffer, the document will only be automatically built on the master branch or on a commit tagged with a `v*` tag.  After the building, the docs will be pushed to the `gh-pages` branch.

Only allowing master-branch or release tag building could prevent docs in a not-yet-approved commit being published. If you want to preview the update, you can build it on the local machine by run `julia ./docs/make.jl`, then start a simple web server which treats the `docs` directory as its root dir:

```
$cd docs
$ python -mSimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```
The point the browser to http://localhost:8080/dev/ to preview the updates.

After the docs being merged into the master branch, it will be automatically built and published.

**Comment by KDr2** [comment]
The CI job is triggered, but there's an error. I will check it ASAP.
https://travis-ci.org/TuringLang/Turing.jl/jobs/590813375

**Comment by trappmartin** [comment]
It doesn't seem that the update of the webpage actually worked, e.g. Library is still called Library instead of API as changed by Cameron through this PR. I suppose something went wrong.

**Comment by trappmartin** [comment]
Side question: Why do we need `DynamicHMC` to build the docs? This seem strange to me.

**Comment by trappmartin** [comment]
For reference:
https://github.com/TuringLang/Turing.jl/blob/4dbb817e1d1484e9b9763c899dd7e0c7d8d23809/.travis.yml#L116
and 
https://github.com/TuringLang/Turing.jl/blob/4dbb817e1d1484e9b9763c899dd7e0c7d8d23809/docs/make.jl#L1

**Comment by trappmartin** [comment]
Which docstring requires this? Would it make sense to get rid of it? It feels wrong that our documentation build depends on DynamicHMC. But maybe thats just me.

**Comment by cpfiffer** [comment]
Well, ignore me, I guess. I was referring to this docstring

https://github.com/TuringLang/Turing.jl/blob/4dbb817e1d1484e9b9763c899dd7e0c7d8d23809/src/contrib/inference/dynamichmc.jl#L9

but we don't appear to be exporting it to the website, so the documentation build step probably doesn't need to include DynamicHMC. Unless we want to export the docstring.

**Pull request merged**
