### PR TITLE
Merge PMCMC samplers into one file - no functionality change. 

### PR DESCRIPTION
**Pull request by yebai**

### CODE REVIEW

**Comment by yebai** [comment]
@trappmartin @cpfiffer @xukai92 @mohamed82008 This PR merges all particle samplers into one file. It uses sections instead of small files to keep functions organised. This approach is used in some Julia base libraries (e.g. `channel.jl`, `task.jl`) I would say this is easier to read and track changes than several smaller files. Any comments/thoughts on why this might be a good/bad practise?

**Comment by mohamed82008** [comment]
I like it. The file is not that big, so I think it is reasonable.

**Comment by cpfiffer** [comment]
I don't see an issue either. Plus, consolidating all the particle samplers might make it easier to have them share interface implementations where possible for #746.

**Comment by trappmartin** [comment]
All the refactoring changes look really good to me too. Thanks for merging files together.

**Pull request merged**
