### PR TITLE
redesign added

### PR DESCRIPTION
**Pull request by gold-developer**

### CODE REVIEW

**Comment by yebai** [comment]
@gold-developer Can you set up a preview of the new design, e.g. on a private server?

cc'ing @cpfiffer

**Comment by gold-developer** [comment]
@yebai , please check this.
https://gold-developer.github.io/turing-docs/

**Comment by cpfiffer** [comment]
@gold-developer nice work, so far. I had a couple of general comments.

First, I think you're taking the VS Code theming too literally. The colors are pretty much directly lifted from the site. We should try to visually distinguish ourselves at least by color. Play around and see what looks nice, and don't just directly use that blue-purple color.

Second, the mini-logo that appears next to the site name in a browser tab now has the incorrect aspect ratio. I'm not sure what's changed there.

Third, the code example on the splash page needs to be in monospace font, not sans font.

Fourth, the buttons under each subsection on the splash page have had their outlines removed, but the padding has remained the same. This means the links are shifted to the right, and it looks pretty bad. 

More generally, I think you should be aware that you have a lot of leeway to build something that is visually interesting. Don't be afraid to change things to look the way you want.

**Comment by gold-developer** [comment]
@yebai , @cpfiffer , updated splash page.
Please check and give me your idea.

**Comment by gold-developer** [comment]
@yebai , @cpfiffer , I updated documentation here:
https://gold-developer.github.io/turingdocs/

Please check it and let me know your opinion.

**Comment by cpfiffer** [comment]
I actually quite like the documentation side. I think the layout in general is well done and it looks very clean. The documentation and tutorials sections are nice and easy to navigate. I have two comments on the navigation bar up top:

1. I think the text should be a little bigger for the "Get Stared", "Documentation", and "Tutorials" links. Right now it looks like they are 1.3 rem -- I think it looks a little better at 1.4rem. Minor change, but still important. 
2. I'm not wild about the logo+navigation bar color. It kind of washes out the logo and makes it look really weird. I don't know if this is a logo problem or a color problem.

As for the splash page, I think it could still use some work. The logo is now tiled, which looks bizarre, and it has the same problem where the background color washes out the logo. I'm not sure what exactly to do about that.

**Comment by xukai92** [comment]
On mobile, clicking the menu button on the left brings you the side with "Home", for which you need to click again to see all the options. Is it easy to have this fixed?

**Comment by gold-developer** [comment]
@cpfiffer , updated navbar font size.
Regarding logo+navigation bar color, I think it will need a new logo than current one, I couldn't get any suitable color for the logo. 

@xukai92 , it was already fixed :)

Please give me further advise.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/pull/861

**Pull request closed without merging**
